class Callsign {
  const Callsign._();

  static const prefixes = <String, String>{
    'Afghanistan': 'T6|YA',
    'Albania': 'ZA',
    'Algeria': '7[RT-Y]',
    'Andorra': 'C3',
    'Angola': 'D[23]',
    'Antigua and Barbuda': 'V2',
    'Argentine Republic': 'A[YZ]|L[2-9O-W]',
    'Armenia': 'EK',
    'Australia': 'AX|V[H-NZ]',
    'Austria': 'OE',
    'Azerbaijan': '4[JK]',
    'Bahamas': 'C6',
    'Bahrain': 'A9',
    'Bangladesh': 'S[23]',
    'Barbados': '8P',
    'Belarus': 'E[U-W]',
    'Belgium': 'O[N-T]',
    'Belize': 'V3',
    'Benin': 'TY',
    'Bhutan': 'A5',
    'Bolivia': 'CP',
    'Bosnia and Herzegovina': 'E7',
    'Botswana': '8O|2A',
    'Brazil': 'P[P-Y]|Z[V-Z]',
    'Brunei Darussalam': 'V8',
    'Bulgaria': 'LZ',
    'Burkina Faso': 'XT',
    'Burundi': '9U',
    'Cabo Verde': 'D4',
    'Cambodia': 'XU',
    'Cameroon': 'TJ',
    'Canada': 'C[F-KYZ]|V[A-GOXY]|X[J-O]',
    'Central African Republic': 'TL',
    'Chad': 'TT',
    'Chile': '3G|C[A-E]|X[QR]',
    'China': '3[H-U]|B[A-Z]|XS|VR|XX',
    // 'China - Hong Kong': 'VR',
    // 'China - Macao': 'XX',
    'Colombia': '[5H][JK]',
    'Comoros': 'D6',
    'Congo': 'TN',
    'Costa Rica': 'T[EI]',
    'Côte d\'Ivoire': 'TU',
    'Croatia': '9A',
    'Cuba': 'C[LMO]|T4',
    'Cyprus': '5B|C4|H2|P3',
    'Czech Republic': 'O[KL]',
    'Democratic People\'s Republic of Korea': 'HM|P[5-9]',
    'Democratic Republic of the Congo': '9[O-T]',
    'Denmark': '5[PQ]|O[U-Z]|XP',
    'Djibouti': 'J2',
    'Dominica': 'J7',
    'Dominican Republic': 'HI',
    'Ecuador': 'H[CD]',
    'Egypt': '6[AB]|S[SU]',
    'El Salvador': 'HU|YS',
    'Equatorial Guinea': '3C',
    'Eritrea': 'E3',
    'Estonia': 'ES',
    'Eswatini': '3D',
    'Ethiopia': '9[EF]|ET',
    'Fiji': '3D',
    'Finland': 'O[F-J]',
    'France': 'F[A-Z]|H[WXY]|T[HKMOPQVWX]',
    'Gabonese Republic': 'TR',
    'Gambia': 'C5',
    'Georgia': '4L',
    'Germany': 'D[A-R]|Y[2-9]',
    'Ghana': '9G',
    'Greece': 'J4|S[V-Z]',
    'Grenada': 'J3',
    'Guatemala': 'T[DG]',
    'Guinea': '3X',
    'Guinea-Bissau': 'J5',
    'Guyana': '8R',
    'Haiti': '4V|HH',
    'Honduras': 'H[QR]',
    'Hungary': 'H[AG]',
    'Iceland': 'TF',
    'India': '8[T-Y]|[AV][T-W]',
    'Indonesia': '[78][A-I]|JZ|P[K-O]|Y[B-H]',
    'International Civil Aviation Organization': '4Y',
    'Iran': '9[BCD]|E[PQ]',
    'Iraq': 'HN|YI',
    'Ireland': 'E[IJ]',
    'Israel': '4[XZ]',
    'Italy': 'I[A-Z]',
    'Jamaica': '6Y',
    'Japan': '[78][J-N]|J[A-S]',
    'Jordan': 'JY',
    'Kazakhstan': 'U[N-Q]',
    'Kenya': '5[YZ]',
    'Kiribati': 'T3',
    'Korea': '6[K-N]|D[789ST]|HL',
    'Kuwait': '9K',
    'Kyrgyz Republic': 'EX',
    'Lao People\'s Democratic Republic': 'XW',
    'Latvia': 'YL',
    'Lebanon': 'OD',
    'Lesotho': '7P',
    'Liberia': '5[LM]|6Z|A8|D5|EL',
    'Libya': '5A',
    'Lithuania': 'LY',
    'Luxembourg': 'LX',
    'Madagascar': '5[RS]|6X',
    'Malawi': '7Q',
    'Malaysia': '9[MW]',
    'Maldives': '8Q',
    'Mali': 'TZ',
    'Malta': '9H',
    'Marshall Islands': 'V7',
    'Mauritania': '5T',
    'Mauritius': '3B',
    'Mexico': '4[ABC]|6[D-J]|X[A-I]',
    'Micronesia': 'V6',
    'Moldova': 'ER',
    'Monaco': '3A',
    'Mongolia': 'J[TUV]',
    'Montenegro': '4O',
    'Morocco': '5[C-G]|CN',
    'Mozambique': 'C[89]',
    'Myanmar': 'X[YZ]',
    'Namibia': 'V5',
    'Nauru': 'C2',
    'Nepal': '9N',
    'Netherlands': 'P[A-J4]',
    // 'Netherlands - Aruba': 'P4',
    // 'Netherlands - Bonaire, Sint Eustatius and Saba': 'PJ',
    // 'Netherlands - Curaçao': 'PJ2',
    // 'Netherlands - Sint Maarten': 'PJ7',
    'New Zealand': 'Z[KLM]|E[56]',
    // 'New Zealand - Cook Islands': 'E5',
    // 'New Zealand - Niue': 'E6',
    'Nicaragua': 'H[67T]|YN',
    'Niger': '5U',
    'Nigeria': '5[NO]',
    'North Macedonia': 'Z3',
    'Norway': '3Y|J[WX]|L[A-N]',
    'Oman': 'A4',
    'Pakistan': '[6A][P-S]',
    'Palau': 'T8',
    'Panama': '3[EF]|H[389OP]',
    'Papua New Guinea': 'P2',
    'Paraguay': 'ZP',
    'Peru': '4T|O[ABC]',
    'Philippines': '4[D-I]|D[U-Z]',
    'Poland': '3Z|HF|S[N-R]',
    'Portugal': 'C[Q-U]',
    'Qatar': 'A7',
    'Romania': 'Y[O-R]',
    'Russian Federation': 'R[A-Z]|U[A-I]',
    'Rwanda': '9X',
    'Saint Kitts and Nevis': 'V4',
    'Saint Lucia': 'J6',
    'Saint Vincent and the Grenadines': 'J8',
    'Samoa': '5W',
    'San Marino': 'T7',
    'Sao Tome and Principe': 'S9',
    'Saudi Arabia': '[78H]Z',
    'Senegal': '6[VW]',
    'Serbia': 'Y[TU]',
    'Seychelles': 'S7',
    'Sierra Leone': '9L',
    'Singapore': '9V|S6',
    'Slovak Republic': 'OM',
    'Slovenia': 'S5',
    'Solomon Islands': 'H4',
    'Somalia': '6O|T5',
    'South Africa': 'S8|Z[R-U]',
    'South Sudan': 'Z8',
    'Spain': 'A[MNO]|E[A-H]',
    'Sri Lanka': '4[P-S]',
    'State of Palestine': 'E4',
    'Sudan': '6[TU]|S[ST]',
    'Suriname': 'PZ',
    'Sweden': '[78]S|S[A-M]',
    'Switzerland': 'H[BE]',
    'Syrian Arab Republic': '6C|YK',
    'Tajikistan': 'EY',
    'Tanzania': '5[HI]',
    'Thailand': 'E2|HS',
    'Timor-Leste': '4W',
    'Togolese Republic': '4W',
    'Tonga': 'A3',
    'Trinidad and Tobago': '9[YZ]',
    'Tunisia': '3V|TS',
    'Turkey': 'T[ABC]|YM',
    'Turkmenistan': 'AZ',
    'Tuvalu': 'T2',
    'Uganda': '5X',
    'Ukraine': 'E[NMO]|U[R-Z]',
    'United Arab Emirates': 'A6',
    'United Kingdom of Great Britain and Northern Ireland':
        '[2GM][A-Z]|V[PQS]|Z[B-JNOQ]',
    'United Nations': '4U',
    'United States of America': 'A[A-L]|[KNW][A-Z]',
    'Uruguay': 'C[V-X]',
    'Uzbekistan': 'U[J-M]',
    'Vanuatu': 'YJ',
    'Vatican City State': 'HV',
    'Venezuela': '4M|Y[V-Y]',
    'Viet Nam': '3W|XV',
    'World Meteorological Organization': 'C7',
    'Yemen': '7O',
    'Zambia': '9[IJ]',
    'Zimbabwe': 'Z2',
  };
}

enum Continent {
  Europe,
  Asia,
  Africa,
  SouthAmerica,
  NorthAmerica,
  Oceania,
  Antartica,
}

class Abc {
  final String name;
  final int dxcc;
  final Continent continent;
  final int timezoneOffset;
  final int ituZone;
  final int cqZone;
  final String flag;
  final String prefix;
  final List<Abc> sub;

  const Abc(
    this.name,
    this.dxcc,
    this.continent,
    this.timezoneOffset,
    this.ituZone,
    this.cqZone,
    this.flag,
    this.prefix, [
    this.sub = const [],
  ]);
}

const a = <Abc>[
  Abc('Afghanistan', 3, Continent.Asia, 5, 40, 21, 'AF', 'T6|YA'),
  Abc('Albania', 7, Continent.Europe, 1, 28, 15, 'AL', 'ZA'),
  Abc('Algeria', 400, Continent.Africa, 0, 37, 33, 'DZ', '7[RT-Y]'),
  Abc('Andaman and Nicobar Islands', 11, Continent.Asia, 6, 49, 26, 'IN'),
  Abc('Andorra', 203, Continent.Europe, 1, 27, 14, 'AD', 'C3'),
  Abc('Angola', 401, Continent.Africa, 1, 52, 36, 'AO', 'D[23]'),
  Abc('Anguilla', 12, Continent.NorthAmerica, -4, 11, 8, 'AI'),
  Abc('Annobon Island', 195, Continent.Africa, -1, 52, 36, 'GQ'),
  Abc('Antarctica', 13, Continent.Antartica, 0, 67, 12, 'AQ'),
  Abc('Antigua and Barbuda', 94, Continent.NorthAmerica, -4, 11, 8, 'AG', 'V2'),
  Abc('Argentina', 100, Continent.SouthAmerica, -3, 14, 13, 'AR',
      'A[YZ]|L[2-9O-W]'),
  Abc('Armenia', 14, Continent.Asia, 4, 29, 21, 'AM', 'EK'),
  Abc('Aruba', 91, Continent.SouthAmerica, -4, 11, 9, 'AW'),
  Abc('Ascension Island', 205, Continent.Africa, 0, 66, 36, 'UK'),
  Abc('Asiatic Russia', 15, Continent.Asia, 7, 20, 16, 'RU'),
  Abc('Auckland, Campbell Islands', 16, Continent.Oceania, 12, 60, 32, 'NZ'),
  Abc('Austral Islands', 508, Continent.Oceania, -10, 63, 32, 'PF'),
  Abc('Australia', 150, Continent.Oceania, 10, 55, 29, 'AU', 'AX|V[H-NZ]'),
// Notes: Australia covers CQ zones 29 and 30. It also has ITU zones 55, 58 and 59.
  Abc('Austria', 206, Continent.Europe, 1, 28, 15, 'AT', 'OE'),
  Abc('Aves Island', 17, Continent.NorthAmerica, -4, 11, 8, 'VE'),
  Abc('Azerbaijan', 18, Continent.Asia, 4, 29, 21, 'AZ', '4[JK]'),
  Abc('Azores', 149, Continent.Europe, -1, 36, 14, 'PT'),
  Abc('Bahamas', 60, Continent.NorthAmerica, -5, 11, 8, 'BS', 'C6'),
  Abc('Bahrain', 304, Continent.Asia, 4, 39, 21, 'BH', 'A9'),
  Abc('Baker and Howland Islands', 20, Continent.Oceania, -12, 61, 31, 'US'),
  Abc('Balearic Islands', 21, Continent.Europe, 1, 37, 14, 'ES'),
  Abc('Banaba Island', 490, Continent.Oceania, 12, 65, 31, 'KI'),
  Abc('Bangladesh', 305, Continent.Asia, 6, 41, 22, 'BD', 'S[23]'),
  Abc('Barbados', 62, Continent.NorthAmerica, -4, 11, 8, 'BB', '8P'),
  Abc('Belarus', 27, Continent.Europe, 2, 29, 16, 'BY', 'E[U-W]'),
  Abc('Belgium', 209, Continent.Europe, 1, 27, 14, 'BE', 'O[N-T]'),
  Abc('Belize', 66, Continent.NorthAmerica, -6, 11, 7, 'BZ', 'V3'),
  Abc('Benin', 416, Continent.Africa, 0, 46, 35, 'BJ', 'TY'),
  Abc('Bermuda', 64, Continent.NorthAmerica, -4, 11, 5, 'BM'),
  Abc('Bhutan', 306, Continent.Asia, 6, 41, 22, 'BT', 'A5'),
  Abc('Bolivia', 104, Continent.SouthAmerica, -4, 12, 10, 'BO', 'CP'),
  Abc('Bonaire', 520, Continent.SouthAmerica, 0, 11, 9, '?'),
  Abc('Bosnia and Herzegovina', 501, Continent.Europe, 1, 28, 15, 'BA', 'E7'),
// Notes: Prefix T9 is the former Bosnia
  Abc('Botswana', 402, Continent.Africa, 2, 57, 38, 'BW', '8O|2A'),
  Abc('Bouvet Island', 24, Continent.Africa, 0, 67, 38, 'BV'),
  Abc('Brazil', 108, Continent.SouthAmerica, -3, 12, 11, 'BR', 'P[P-Y]|Z[V-Z]'),
  Abc('British Virgin Islands', 65, Continent.NorthAmerica, -4, 11, 8, 'VG'),
  Abc('Brunei', 345, Continent.Oceania, 8, 54, 28, 'BN', 'V8'),
  Abc('Bulgaria', 212, Continent.Europe, 2, 28, 20, 'BG', 'LZ'),
  Abc('Burkina Faso', 480, Continent.Africa, 0, 46, 35, 'BF', 'XT'),
  Abc('Burundi', 404, Continent.Africa, 3, 52, 36, 'BI', '9U'),
  Abc('Cambodia', 312, Continent.Asia, 8, 49, 26, 'KH', 'XU'),
  Abc('Cameroon', 406, Continent.Africa, 1, 47, 36, 'CM', 'TJ'),
  Abc('Canada', 1, Continent.NorthAmerica, -5, 2, 1, 'CA',
      'C[F-KYZ]|V[A-GOXY]|X[J-O]'),
  Abc('Canary Islands', 29, Continent.Africa, 0, 36, 33, 'ES'),
  Abc('Cape Verde', 409, Continent.Africa, -2, 46, 35, 'CV', 'D4'),
  Abc('Cayman Islands', 69, Continent.NorthAmerica, -5, 11, 8, 'KY'),
  Abc('Central African Republic', 408, Continent.Africa, 1, 47, 36, 'CF', 'TL'),
  Abc('Central Kiribati', 31, Continent.Oceania, 12, 62, 31, 'KI'),
  Abc('Ceuta and Melilla', 32, Continent.Africa, 1, 37, 33, 'ES'),
  Abc('Chad', 410, Continent.Africa, 1, 47, 36, 'TD', 'TT'),
  Abc('Chagos Islands', 33, Continent.Africa, 5, 41, 39, 'GB'),
  Abc('Chatham Islands', 34, Continent.Oceania, 13, 60, 32, 'NZ'),
  Abc('Chesterfield Islands', 512, Continent.Oceania, 11, 55, 30, 'GB'),
  Abc('Chile', 112, Continent.SouthAmerica, -4, 14, 12, 'CL',
      '3G|C[A-E]|X[QR]'),
  Abc('China', 318, Continent.Asia, 8, 33, 23, 'CN', '3[H-U]|B[A-Z]|XS|VR|XX'),
  Abc('Christmas Island', 35, Continent.Oceania, 7, 54, 29, 'CX'),
  Abc('Clipperton Island', 36, Continent.NorthAmerica, -7, 10, 7, 'FR'),
  Abc('Cocos Island', 37, Continent.NorthAmerica, -6, 11, 7, 'CR'),
  Abc('Cocos-Keeling Islands', 38, Continent.Oceania, 7, 54, 29, 'CC'),
  Abc('Colombia', 116, Continent.SouthAmerica, -5, 12, 9, 'CO', '[5H][JK]'),
  Abc('Comoros', 411, Continent.Africa, 3, 53, 39, 'KM', 'D6'),
  Abc('Congo', 412, Continent.Africa, 1, 52, 36, 'CG', 'TN'),
  Abc('Democratic Republic of the Congo', 414, Continent.Africa, 1, 52, 36,
      'CD'),
  Abc('Conway Reef', 489, Continent.Oceania, 12, 56, 32, 'FJ'),
  Abc('Corsica', 214, Continent.Europe, 1, 28, 15, 'FR'),
  Abc('Costa Rica', 308, Continent.NorthAmerica, -6, 11, 7, 'CR', 'T[EI]'),
  Abc('Crete', 40, Continent.Europe, 2, 28, 20, 'GR'),
  Abc('Croatia', 497, Continent.Europe, 1, 28, 15, 'HR', '9A'),
  Abc('Crozet Island', 41, Continent.Africa, 3, 68, 39, 'FR'),
  Abc('Cuba', 70, Continent.NorthAmerica, -5, 11, 8, 'CU', 'C[LMO]|T4'),
  Abc('Curacao', 517, Continent.SouthAmerica, -4, 11, 9, 'AN'),
  Abc('Cyprus', 215, Continent.Asia, 3, 39, 20, 'CY', '5B|C4|H2|P3'),
  Abc('Cyprus SBA', 283, Continent.Asia, 2, 39, 20, 'CY'),
// Notes: SBA = Sovereign Base Areas
  Abc('Czech Republic', 503, Continent.Europe, 1, 28, 15, 'CZ', 'O[KL]'),
  Abc('Denmark', 221, Continent.Europe, 1, 18, 14, 'DK', '5[PQ]|O[U-Z]|XP'),
  Abc('Desecheo Island', 43, Continent.NorthAmerica, -4, 11, 8, 'PR'),
  Abc('Djibouti', 382, Continent.Africa, 3, 48, 37, 'DJ', 'J2'),
  Abc('Dodecanese', 45, Continent.Europe, 2, 28, 20, 'GR'),
  Abc('Dominica', 95, Continent.NorthAmerica, -4, 11, 8, 'DM', 'J7'),
  Abc('Dominican Republic', 72, Continent.NorthAmerica, -4, 11, 8, 'DO', 'HI'),
  Abc('Ducie Island', 513, Continent.Oceania, -9, 63, 32, 'PN'),
  Abc('East Kiribati', 48, Continent.Oceania, 12, 61, 31, 'KI'),
  Abc('East Malaysia', 46, Continent.Oceania, 8, 54, 28, 'MY'),
  Abc('Easter Island', 47, Continent.SouthAmerica, -7, 63, 12, 'CL'),
  Abc('Ecuador', 120, Continent.SouthAmerica, -5, 12, 10, 'EC', 'H[CD]'),
  Abc('Egypt', 478, Continent.Africa, 2, 38, 34, 'EG', '6[AB]|S[SU]'),
  Abc('El Salvador', 74, Continent.NorthAmerica, -6, 11, 7, 'SV', 'HU|YS'),
  Abc('England', 223, Continent.Europe, 0, 27, 14, 'GB',
      '[2GM][A-Z]|V[PQS]|Z[B-JNOQ]'),
  Abc('Equatorial Guinea', 49, Continent.Africa, -1, 47, 36, 'GQ', '3C'),
  Abc('Eritrea', 51, Continent.Africa, 3, 48, 37, 'ER', 'E3'),
  Abc('Estonia', 52, Continent.Europe, 2, 29, 15, 'EE', 'ES'),
  Abc('Eswatini', 468, Continent.Africa, 2, 57, 38, 'SZ', '3D'),
  Abc('Ethiopia', 53, Continent.Africa, 3, 48, 37, 'ET', '9[EF]|ET'),
  Abc('Falkland Islands', 141, Continent.SouthAmerica, -4, 16, 13, 'FK'),
  Abc('Faroe Islands', 222, Continent.Europe, 0, 18, 14, 'FO'),
  Abc('Fernando de Noronha', 56, Continent.SouthAmerica, -2, 13, 11, 'BR'),
  Abc('Fiji', 176, Continent.Oceania, 12, 56, 32, 'FJ', '3D'),
  Abc('Finland', 224, Continent.Europe, 2, 18, 15, 'FI', 'O[F-J]', [
    Abc('Aland Islands', 5, Continent.Europe, 2, 18, 15, 'AX', 'OH0'),
  ]),
  Abc('France', 227, Continent.Europe, 1, 27, 14, 'FR',
      'F[A-Z]|H[WXY]|T[HKMOPQVWX]', [
    Abc('Amsterdam and St Paul Islands', 10, Continent.Africa, 5, 68, 39, 'FR'),
  ]),
  Abc('Franz Josef Land', 61, Continent.Europe, 3, 75, 40, 'RU'),
  Abc('French Guiana', 63, Continent.SouthAmerica, -4, 12, 9, 'GF'),
  Abc('French Polynesia', 175, Continent.Oceania, -10, 63, 32, 'PF'),
  Abc('Gabon', 420, Continent.Africa, 1, 52, 36, 'GA', 'TR'),
  Abc('Galapagos Islands', 71, Continent.SouthAmerica, -6, 12, 10, 'EC'),
  Abc('Georgia', 75, Continent.Asia, 4, 29, 21, 'GE', '4L'),
  Abc('Germany', 230, Continent.Europe, 1, 28, 14, 'DE', 'D[A-R]|Y[2-9]'),
  Abc('Ghana', 424, Continent.Africa, 0, 46, 35, 'GH', '9G'),
  Abc('Gibraltar', 233, Continent.Europe, 1, 37, 14, 'GI'),
  Abc('Glorioso Islands', 99, Continent.Africa, 3, 53, 39, 'FR'),
  Abc('Greece', 236, Continent.Europe, 2, 28, 20, 'GR', 'J4|S[V-Z]'),
  Abc('Greenland', 237, Continent.NorthAmerica, -3, 5, 40, 'GL'),
  Abc('Grenada', 77, Continent.NorthAmerica, -4, 11, 8, 'GD', 'J3'),
  Abc('Guadeloupe', 79, Continent.NorthAmerica, -4, 11, 8, 'GP'),
  Abc('Guam', 103, Continent.Oceania, 10, 64, 27, 'GU'),
  Abc('Guantanamo Bay', 105, Continent.NorthAmerica, -5, 11, 8, 'US'),
  Abc('Guatemala', 76, Continent.NorthAmerica, -6, 11, 7, 'GT', 'T[DG]'),
  Abc('Guernsey', 106, Continent.Europe, 0, 27, 14, 'GG'),
  Abc('Guinea', 107, Continent.Africa, 0, 46, 35, 'GN', '3X'),
  Abc('Guinea-Bissau', 109, Continent.Africa, -1, 46, 35, 'GW', 'J5'),
  Abc('Guyana', 129, Continent.SouthAmerica, -4, 12, 9, 'GY', '8R'),
  Abc('Haiti', 78, Continent.NorthAmerica, -5, 11, 8, 'HT', '4V|HH'),
  Abc('Hawaii', 110, Continent.Oceania, -10, 61, 31, 'US'),
  Abc('Heard Islands', 111, Continent.Africa, 5, 68, 39, 'HM'),
  Abc('Honduras', 80, Continent.NorthAmerica, -6, 11, 7, 'HN', 'H[QR]'),
  Abc('Hong Kong', 321, Continent.Asia, 8, 44, 24, 'HK'),
  Abc('Hungary', 239, Continent.Europe, 1, 28, 15, 'HU', 'H[AG]'),
  Abc('Iceland', 242, Continent.Europe, 0, 17, 40, 'IS', 'TF'),
  Abc('India', 324, Continent.Asia, 6, 41, 22, 'IN', '8[T-Y]|[AV][T-W]'),
  Abc('Indonesia', 327, Continent.Oceania, 8, 51, 28, 'ID',
      '[78][A-I]|JZ|P[K-O]|Y[B-H]'),
  Abc('Iran', 330, Continent.Asia, 4, 40, 21, 'IR', '9[BCD]|E[PQ]'),
  Abc('Iraq', 333, Continent.Asia, 3, 39, 21, 'IQ', 'HN|YI'),
  Abc('Ireland', 245, Continent.Europe, 0, 27, 14, 'IE', 'E[IJ]'),
  Abc('Isle of Man', 114, Continent.Europe, 0, 27, 14, 'IM'),
  Abc('Israel', 336, Continent.Asia, 2, 39, 20, 'IL', '4[XZ]'),
  Abc('Italy', 248, Continent.Europe, 1, 28, 15, 'IT', 'I[A-Z]'),
  Abc('ITU Geneva', 117, Continent.Europe, 1, 28, 14, 'CH'),
  Abc('Ivory Coast', 428, Continent.Africa, 0, 46, 35, 'CI', 'TU'),
// Notes: aka C⌠te d'Ivoire
  Abc('Jamaica', 82, Continent.NorthAmerica, -5, 11, 8, 'JM', '6Y'),
  Abc('Jan Mayen Island', 118, Continent.Europe, -1, 18, 40, 'SJ'),
  Abc('Japan', 339, Continent.Asia, 9, 45, 25, 'JP', '[78][J-N]|J[A-S]'),
  Abc('Jersey', 122, Continent.Europe, 0, 27, 14, 'JE'),
  Abc('Johnston Island', 123, Continent.Oceania, -11, 61, 31, 'US'),
  Abc('Jordan', 342, Continent.Asia, 2, 39, 20, 'JO', 'JY'),
  Abc('Juan de Nova Island', 124, Continent.Africa, 3, 53, 39, 'FR'),
  Abc('Juan Fernandez Islands', 125, Continent.SouthAmerica, -4, 14, 12, 'CL'),
  Abc('Kaliningrad', 126, Continent.Europe, 2, 29, 15, 'RU'),
  Abc('Kazakhstan', 130, Continent.Asia, 6, 29, 17, 'KZ', 'U[N-Q]'),
  Abc('Kenya', 430, Continent.Africa, 3, 48, 37, 'KE', '5[YZ]'),
  Abc('Kerguelen Islands', 131, Continent.Africa, 5, 68, 39, 'FR'),
  Abc('Kermadec Islands', 133, Continent.Oceania, 12, 60, 32, 'NZ'),
  Abc('Kingman Reef', 134, Continent.Oceania, -11, 61, 31, 'US'),
  Abc('Kiribati', 301, Continent.Oceania, 12, 65, 31, 'KI', 'T3'),
  Abc('Kure Atoll', 138, Continent.Oceania, -11, 61, 31, 'US'),
  Abc('Kuwait', 348, Continent.Asia, 3, 39, 21, 'KW', '9K'),
  Abc('Kyrgyzstan', 135, Continent.Asia, 6, 30, 17, 'KG', 'EX'),
  Abc('Lakshadweep Islands', 142, Continent.Asia, 6, 41, 22, 'IN'),
  Abc('Laos', 143, Continent.Asia, 7, 49, 26, 'LA', 'XW'),
  Abc('Latvia', 145, Continent.Europe, 2, 29, 15, 'LV', 'YL'),
  Abc('Lebanon', 354, Continent.Asia, 2, 39, 20, 'LB', 'OD'),
  Abc('Lesotho', 432, Continent.Africa, 2, 57, 38, 'LS', '7P'),
  Abc('Liberia', 434, Continent.Africa, -1, 46, 35, 'LR', '5[LM]|6Z|A8|D5|EL'),
  Abc('Libya', 436, Continent.Africa, 2, 38, 34, 'LY', '5A'),
  Abc('Liechtenstein', 251, Continent.Europe, 1, 28, 14, 'LI'),
  Abc('Lithuania', 146, Continent.Europe, 2, 29, 15, 'LT', 'LY'),
  Abc('Lord Howe Island', 147, Continent.Oceania, 10, 60, 30, 'AU'),
  Abc('Luxembourg', 254, Continent.Europe, 1, 27, 14, 'LU', 'LX'),
  Abc('Macau', 152, Continent.Asia, 8, 44, 24, 'MO'),
  Abc('Macquarie Island', 153, Continent.Oceania, 11, 60, 30, 'AU'),
  Abc('Madagascar', 438, Continent.Africa, 3, 53, 39, 'MG', '5[RS]|6X'),
  Abc('Madeira Island', 256, Continent.Africa, -1, 36, 33, 'PT'),
  Abc('Malawi', 440, Continent.Africa, 2, 53, 37, 'MW', '7Q'),
  Abc('Maldives', 159, Continent.Asia, 5, 41, 22, 'MV', '8Q'),
  Abc('Mali', 442, Continent.Africa, 0, 46, 35, 'ML', 'TZ'),
  Abc('Malpelo Island', 161, Continent.SouthAmerica, -5, 12, 9, 'CO'),
  Abc('Malta', 257, Continent.Europe, 1, 28, 15, 'MT', '9H'),
  Abc('Mariana Islands', 166, Continent.Oceania, 10, 64, 27, 'US'),
  Abc('Market Reef', 167, Continent.Europe, 2, 18, 15, 'SE'),
  Abc('Marquesas Islands', 509, Continent.Oceania, -10, 63, 31, 'FR'),
  Abc('Marshall Islands', 168, Continent.Oceania, 12, 65, 31, 'MH', 'V7'),
  Abc('Martinique', 84, Continent.NorthAmerica, -4, 11, 8, 'MQ'),
  Abc('Mauritania', 444, Continent.Africa, -1, 46, 35, 'MR', '5T'),
  Abc('Mauritius', 165, Continent.Africa, 4, 53, 39, 'MU', '3B', [
    Abc('Agalega and St Brandon', 4, Continent.Africa, 4, 53, 39, 'MP',
        '3B[67]'),
  ]),
  Abc('Mayotte', 169, Continent.Africa, 3, 53, 39, 'YT'),
  Abc('Mellish Reef', 171, Continent.Oceania, 10, 55, 30, 'AU'),
  Abc('Mexico', 50, Continent.NorthAmerica, -6, 10, 6, 'MX',
      '4[ABC]|6[D-J]|X[A-I]'),
  Abc('Micronesia', 173, Continent.Oceania, 11, 65, 27, 'FM', 'V6'),
  Abc('Midway Islands', 174, Continent.Oceania, -11, 61, 31, 'US'),
  Abc('Minami Torishima', 177, Continent.Oceania, 10, 90, 27, 'JP'),
  Abc('Moldova', 179, Continent.Europe, 3, 29, 16, 'MD', 'ER'),
  Abc('Monaco', 260, Continent.Europe, 1, 27, 14, 'MC', '3A'),
  Abc('Mongolia', 363, Continent.Asia, 8, 32, 23, 'MN', 'J[TUV]'),
  Abc('Montenegro', 514, Continent.Europe, 1, 28, 15, 'ME', '4O'),
  Abc('Montserrat', 96, Continent.NorthAmerica, -4, 11, 8, 'MS'),
  Abc('Morocco', 446, Continent.Africa, 0, 37, 33, 'MA', '5[C-G]|CN'),
  Abc('Mozambique', 181, Continent.Africa, 2, 53, 37, 'MZ', 'C[89]'),
  Abc('Mt Athos', 180, Continent.Europe, 2, 28, 20, 'GR'),
  Abc('Myanmar (Burma)', 309, Continent.Asia, 7, 49, 26, 'MM', 'X[YZ]'),
  Abc('Namibia', 464, Continent.Africa, 2, 57, 38, 'NA', 'V5'),
  Abc('Nauru', 157, Continent.Oceania, 12, 65, 31, 'NR', 'C2'),
  Abc('Navassa Island', 182, Continent.NorthAmerica, -5, 11, 8, 'US'),
  Abc('Nepal', 369, Continent.Asia, 545, 42, 22, 'NP', '9N'),
  Abc('Netherlands', 263, Continent.Europe, 1, 27, 14, 'NL', 'P[A-J4]'),
  Abc('New Caledonia', 162, Continent.Oceania, 11, 56, 32, 'NC'),
  Abc('New Zealand', 170, Continent.Oceania, 12, 60, 32, 'NZ', 'Z[KLM]|E[56]'),
  Abc('Nicaragua', 86, Continent.NorthAmerica, -6, 11, 7, 'NI', 'H[67T]|YN'),
  Abc('Niger', 187, Continent.Africa, 1, 46, 35, 'NE', '5U'),
  Abc('Nigeria', 450, Continent.Africa, 1, 46, 35, 'NG', '5[NO]'),
  Abc('Niue', 188, Continent.Oceania, -11, 62, 32, 'NU'),
  Abc('Norfolk Island', 189, Continent.Oceania, 12, 60, 32, 'NF'),
  Abc('North Cook Islands', 191, Continent.Oceania, -11, 62, 32, 'NZ'),
  Abc('North Korea', 344, Continent.Asia, 9, 44, 25, 'KP'),
  Abc('North Macedonia', 502, Continent.Europe, 1, 28, 15, 'MK', 'Z3'),
  Abc('Northern Cyprus', 901, Continent.Asia, 2, 39, 20, '?'),
// Notes: Not recgonized by the ITU, ARRL, or UN. Also known as the Turkish Republic of Northern Cyprus
  Abc('Northern Ireland', 265, Continent.Europe, 0, 27, 14, 'IE'),
  Abc('Norway', 266, Continent.Europe, 1, 18, 14, 'NO', '3Y|J[WX]|L[A-N]'),
  Abc('Ogasawara', 192, Continent.Asia, 10, 45, 27, 'JP'),
  Abc('Oman', 370, Continent.Asia, 4, 39, 21, 'OM', 'A4'),
  Abc('Pakistan', 372, Continent.Asia, 5, 41, 21, 'PK', '[6A][P-S]'),
  Abc('Palau', 22, Continent.Oceania, 10, 64, 27, 'PW', 'T8'),
  Abc('Palestine', 510, Continent.Asia, 2, 39, 20, 'PS', 'E4'),
  Abc('Palmyra, Jarvis Island', 197, Continent.Oceania, -11, 61, 31, 'US'),
  Abc('Panama', 88, Continent.NorthAmerica, -5, 11, 7, 'PA', '3[EF]|H[389OP]'),
  Abc('Papua New Guinea', 163, Continent.Oceania, 10, 51, 28, 'PG', 'P2'),
  Abc('Paraguay', 132, Continent.SouthAmerica, -4, 14, 11, 'PY', 'ZP'),
  Abc('Peru', 136, Continent.SouthAmerica, -5, 12, 10, 'PE', '4T|O[ABC]'),
  Abc('Peter I Island', 199, Continent.Antartica, -6, 72, 12, 'NO'),
  Abc('Philippines', 375, Continent.Oceania, 8, 50, 27, 'PH', '4[D-I]|D[U-Z]'),
  Abc('Pitcairn Islands', 172, Continent.Oceania, -9, 63, 32, 'PN'),
  Abc('Poland', 269, Continent.Europe, 1, 28, 15, 'PL', '3Z|HF|S[N-R]'),
  Abc('Portugal', 272, Continent.Europe, 0, 37, 14, 'PT', 'C[Q-U]'),
  Abc('Pratas Island', 505, Continent.Asia, 8, 44, 24, 'TW'),
  Abc('Prince Edward and Marion Island', 201, Continent.Africa, 3, 57, 38,
      'ZA'),
  Abc('Puerto Rico', 202, Continent.NorthAmerica, -4, 11, 8, 'PR'),
  Abc('Qatar', 376, Continent.Asia, 4, 39, 21, 'QA', 'A7'),
  Abc('Republic of Kosovo', 522, Continent.Europe, 1, 28, 15, '?'),
  Abc('Reunion', 453, Continent.Africa, 4, 53, 39, 'RE'),
// Notes: As of feb 20 2015 they use french flag)
  Abc('Revillagigedo Islands', 204, Continent.NorthAmerica, -7, 10, 6, 'MX'),
  Abc('Rodriguez Island', 207, Continent.Africa, 4, 53, 39, 'MU'),
  Abc('Romania', 275, Continent.Europe, 2, 28, 20, 'RO', 'Y[O-R]'),
  Abc('Rotuma', 460, Continent.Oceania, 12, 56, 32, 'FJ'),
  Abc('Russia', 54, Continent.Europe, 3, 19, 16, 'RU', 'R[A-Z]|U[A-I]'),
  Abc('Rwanda', 454, Continent.Africa, 3, 52, 36, 'RW', '9X'),
  Abc('Saba, St Eustatius', 519, Continent.NorthAmerica, -4, 11, 8, 'AN'),
  Abc('Sable Island', 211, Continent.NorthAmerica, -5, 9, 5, 'CA'),
  Abc('Samoa', 190, Continent.Oceania, -11, 62, 32, 'WS', '5W'),
  Abc('San Andres and Providencia', 216, Continent.NorthAmerica, -6, 11, 7,
      'NI'),
  Abc('San Felix', 217, Continent.SouthAmerica, -5, 14, 12, 'CL'),
  Abc('San Marino', 278, Continent.Europe, 1, 28, 15, 'SM', 'T7'),
  Abc('Sao Tome & Principe', 219, Continent.Africa, 0, 47, 36, 'ST', 'S9'),
  Abc('Sardinia', 225, Continent.Europe, 1, 28, 15, 'IT'),
  Abc('Saudi Arabia', 378, Continent.Asia, 3, 39, 21, 'SA', '[78H]Z'),
  Abc('Saudi Arabia/Iraq Neutral Zone', 1378, Continent.Asia, 3, 39, 21, 'SA'),
  Abc('Scarborough Reef', 506, Continent.Asia, 8, 50, 27, '?'),
  Abc('Scotland', 279, Continent.Europe, 0, 27, 14, 'GB'),
  Abc('Senegal', 456, Continent.Africa, 0, 46, 35, 'SN', '6[VW]'),
  Abc('Serbia', 296, Continent.Europe, 1, 28, 15, 'RS', 'Y[TU]'),
// Notes: Prefix 4N is the former Serbia
  Abc('Seychelles', 379, Continent.Africa, 4, 53, 39, 'SC', 'S7'),
  Abc('Sierra Leone', 458, Continent.Africa, 0, 46, 35, 'SL', '9L'),
  Abc('Singapore', 381, Continent.Asia, 8, 54, 28, 'SG', '9V|S6'),
  Abc('Slovak Republic', 504, Continent.Europe, 1, 28, 15, 'SK', 'OM'),
  Abc('Slovenia', 499, Continent.Europe, 1, 28, 15, 'SI', 'S5'),
  Abc('SMO Malta', 246, Continent.Europe, 1, 28, 15, 'MT'),
// Notes: Sovereign Military Order of Malta - DXCC but not a country per se.
  Abc('Solomon Islands', 185, Continent.Oceania, 11, 51, 28, 'SB', 'H4'),
  Abc('Somalia', 232, Continent.Africa, 3, 48, 37, 'SO', '6O|T5'),
  Abc('South Africa', 462, Continent.Africa, 2, 57, 38, 'ZA', 'S8|Z[R-U]'),
  Abc('South Cook Islands', 234, Continent.Oceania, -11, 63, 32, 'GS'),
  Abc('South Georgia Islands', 235, Continent.SouthAmerica, -2, 73, 13, 'GS'),
  Abc('South Korea', 137, Continent.Asia, 9, 44, 25, 'KR',
      '6[K-N]|D[789ST]|HL'),
  Abc('South Orkney Islands', 238, Continent.SouthAmerica, -3, 73, 13, 'GB'),
  Abc('South Sandwich Islands', 240, Continent.SouthAmerica, -3, 73, 13, 'GS'),
  Abc('South Shetland Islands', 241, Continent.SouthAmerica, -4, 73, 13, 'GB'),
  Abc('South Sudan', 521, Continent.Africa, 0, 0, 0, 'SS', 'Z8'),
  Abc('Spain', 281, Continent.Europe, 1, 37, 14, 'ES', 'A[MNO]|E[A-H]'),
  Abc('Spratly Islands', 247, Continent.Asia, 7, 50, 26, 'PH'),
  Abc('Sri Lanka', 315, Continent.Asia, 6, 41, 22, 'LK', '4[P-S]'),
  Abc('St Helena Island', 250, Continent.Africa, 0, 66, 36, 'SH'),
  Abc('St Kitts and Nevis', 249, Continent.NorthAmerica, -4, 11, 8, 'KN', 'V4'),
  Abc('St Lucia', 97, Continent.NorthAmerica, -4, 11, 8, 'LC', 'J6'),
  Abc('St Martin', 213, Continent.NorthAmerica, -4, 11, 8, 'FR'),
  Abc('St Paul Island', 252, Continent.NorthAmerica, -5, 9, 5, 'CA'),
  Abc('St Peter & St Paul Rocks', 253, Continent.SouthAmerica, -2, 13, 11,
      'BR'),
  Abc('St Pierre & Miquelon', 277, Continent.NorthAmerica, -4, 9, 5, 'CA'),
  Abc('St Vincent', 98, Continent.NorthAmerica, -4, 11, 8, 'VC', 'J8'),
  Abc('St. Barthelemy', 516, Continent.NorthAmerica, 0, 0, 0, '?'),
  Abc('St. Maarten', 518, Continent.NorthAmerica, 0, 11, 8, '?'),
  Abc('Sudan', 466, Continent.Africa, 2, 48, 34, 'SD', '6[TU]|S[ST]'),
  Abc('Suriname', 140, Continent.SouthAmerica, -4, 12, 9, 'SR', 'PZ'),
  Abc('Svalbard', 259, Continent.Europe, 1, 18, 40, 'SJ'),
  Abc('Swains Island', 515, Continent.Oceania, -11, 62, 32, 'US'),
  Abc('Sweden', 284, Continent.Europe, 1, 18, 14, 'SE', '[78]S|S[A-M]'),
  Abc('Switzerland', 287, Continent.Europe, 1, 28, 14, 'CH', 'H[BE]'),
  Abc('Syria', 384, Continent.Asia, 2, 39, 20, 'SY', '6C|YK'),
  Abc('Taiwan', 386, Continent.Asia, 8, 44, 24, 'TW'),
  Abc('Tajikistan', 262, Continent.Asia, 6, 30, 17, 'TJ', 'EY'),
  Abc('Tanzania', 470, Continent.Africa, 3, 53, 37, 'TZ', '5[HI]'),
  Abc('Temotu', 507, Continent.Oceania, 11, 51, 28, 'SB'),
  Abc('Thailand', 387, Continent.Asia, 7, 49, 26, 'TH', 'E2|HS'),
  Abc('The Gambia', 422, Continent.Africa, 0, 46, 35, 'GM', 'C5'),
  Abc('Timor Leste', 511, Continent.Oceania, 8, 54, 28, 'TL', '4W'),
// Notes: A.K.A. East Timor
  Abc('Togo', 483, Continent.Africa, 0, 46, 35, 'TG', '4W'),
  Abc('Tokelau Islands', 270, Continent.Oceania, -11, 62, 31, 'TK'),
  Abc('Tonga', 160, Continent.Oceania, 13, 62, 32, 'TO', 'A3'),
  Abc('Trindade and Martim Vaz Island', 273, Continent.SouthAmerica, -2, 15, 11,
      'BR'),
  Abc('Trinidad and Tobago', 90, Continent.SouthAmerica, -4, 11, 9, 'TT',
      '9[YZ]'),
  Abc('Tristan da Cunha and Gough Island', 274, Continent.Africa, 0, 66, 38,
      'GB'),
  Abc('Tromelin Island', 276, Continent.Africa, 4, 53, 39, 'FR'),
  Abc('Tunisia', 474, Continent.Africa, 1, 37, 33, 'TN', '3V|TS'),
  Abc('Turkey', 390, Continent.Asia, 2, 39, 20, 'TR', 'T[ABC]|YM'),
  Abc('Turkmenistan', 280, Continent.Asia, 5, 30, 17, 'TM', 'AZ'),
  Abc('Turks and Caicos Islands', 89, Continent.NorthAmerica, -5, 11, 8, 'TC'),
  Abc('Tuvalu', 282, Continent.Oceania, 12, 65, 31, 'TV', 'T2'),
  Abc('Uganda', 286, Continent.Africa, 3, 48, 37, 'UG', '5X'),
  Abc('Ukraine', 288, Continent.Europe, 2, 29, 16, 'UA', 'E[NMO]|U[R-Z]'),
  Abc('United Arab Emirates', 391, Continent.Asia, 4, 39, 21, 'AE', 'A6'),
  Abc('United Nations', 289, Continent.NorthAmerica, -5, 8, 5, 'UN', '4U'),
// Notes: 4U70UN
  Abc('United States', 291, Continent.NorthAmerica, -5, 0, 0, 'US',
      'A[A-L]|[KNW][A-Z]', [
    Abc('Alaska', 6, Continent.NorthAmerica, -8, 1, 1, 'US', '[AKNW]L'),
    Abc('American Samoa', 9, Continent.Oceania, -11, 62, 32, 'AS', '[AKNW]H8'),
  ]),
  Abc('Uruguay', 144, Continent.SouthAmerica, -3, 14, 13, 'UY', 'C[V-X]'),
  Abc('US Virgin Islands', 285, Continent.NorthAmerica, -4, 11, 8, 'VI'),
  Abc('Uzbekistan', 292, Continent.Asia, 6, 30, 17, 'UZ', 'U[J-M]'),
  Abc('Vanuatu', 158, Continent.Oceania, 11, 56, 32, 'VU', 'YJ'),
  Abc('Vatican', 295, Continent.Europe, 1, 28, 15, 'VA', 'HV'),
  Abc('Venezuela', 148, Continent.SouthAmerica, -4, 12, 9, 'VE', '4M|Y[V-Y]'),
  Abc('Vietnam', 293, Continent.Asia, 7, 49, 26, 'VN', '3W|XV'),
  Abc('Wake Island', 297, Continent.Oceania, 12, 65, 31, 'US'),
  Abc('Wales', 294, Continent.Europe, 0, 27, 14, 'GB'),
  Abc('Wallis and Futuna Islands', 298, Continent.Oceania, -11, 62, 32, 'WF'),
  Abc('West Malaysia', 299, Continent.Asia, 8, 54, 28, 'MY'),
  Abc('Western Sahara', 302, Continent.Africa, 0, 46, 33, 'EH'),
  Abc('Willis Island', 303, Continent.Oceania, 10, 55, 30, 'AU'),
  Abc('Yemen', 492, Continent.Asia, 3, 39, 21, 'YE', '7O'),
  Abc('Zambia', 482, Continent.Africa, 2, 53, 36, 'ZM', '9[IJ]'),
  Abc('Zimbabwe', 452, Continent.Africa, 2, 53, 38, 'ZW', 'Z2'),
];
